# This workflow is provided just as an usage example and not for repo testing/verification
name: alpine6-node-base

on:
  push:
    branches:
      - 'main'
  pull_request:

env:
  DOCKER_IMAGE: localhost:5000/name/app

jobs:
  docker:
    runs-on: ubuntu-latest
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
        steps:
    
        - name: Check Out Repo 
          uses: actions/checkout@v2

        - name: Login to Docker Hub
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKER_HUB_USERNAME }}
            password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

        - name: Set up Docker Buildx
          id: buildx
          uses: docker/setup-buildx-action@v1

        - name: Build and push
          id: docker_build
          uses: docker/build-push-action@v2
          with:
            context: ./
            file: ./Dockerfile
            push: true
            tags: ${{ secrets.DOCKER_HUB_USERNAME }}/alpine6-node-base:latest

        - name: Image digest
          run: echo ${{ steps.docker_build.outputs.digest }}
